### ISSUE TITLE
Beta 1 feedback

### ISSUE THREAD

**Issue by Madis0** [Minenash/Enhanced-Attack-Indicator#11]
I tested the beta 1 out and I think you could word and order the settings as following (including parentheses, maybe as a tooltip if possible):
1. Attack Cooldown Priority: First/Middle/Last 
2. Ranged Weapon Draw (Bow, Crossbow, Trident, ...): Draw/Mine/Both/Neither
3. Special Item Cooldowns (Ender Pearl, Chorus Fruit, ...): Use/Mine/Both/Neither
4. Axe Cooldown: Attack/Mine/Both/Neither
5. Non-Weapon Tools Cooldown (Pickaxe, Shovel, ...): Attack/Mine/Both/Neither
6. Empty Hand / Other Items: Attack/Mine/Both/Neither

This wording is better as it can include modded items, which you were concerned about lacking an option for. "Other Items" can also be worded as "Items with Default Cooldown".

**Comment by Minenash** [comment]
Closing this as I abandoned the beta, and don't think I'll revisit it
