### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by legosteenjaap** [Minenash/Enhanced-Attack-Indicator#12]
[crash-2021-06-01_13.59.51-client.txt](https://github.com/Minenash/Enhanced-Attack-Indicator/files/6576032/crash-2021-06-01_13.59.51-client.txt)

**Comment by Minenash** [comment]
I can't replicate this. It works fine for me on both 1.17-pre2 and 1.17-pre3. Can you try with 1.17-pre3? If that still doesn't work, can you try a jvm that isn't GraalVM?

**Comment by legosteenjaap** [comment]
Oh wait i made a mistake in the title. I meant to say that the game crashes when i enter a world, did you do that? And no it doesn't work in pre-3 or graalvm.

**Comment by Minenash** [comment]
I didn't join the world because of the tile. I can though.

> And no it doesn't work in pre-3 or graalvm.

Well to be fair, I did say *not* Graal

**Comment by legosteenjaap** [comment]
I mean't removing graal sorry

**Comment by Minenash** [comment]
I loaded into the world, I still can't reproduce

**Comment by Minenash** [comment]
I kinda doubt this would fix it, but can you make a fresh instance, with a fresh install of both fabric loader and the api?

**Comment by legosteenjaap** [comment]
sure

**Comment by legosteenjaap** [comment]
nope it crashed again

**Comment by Minenash** [comment]
Same exact error I'm assuming?

**Comment by legosteenjaap** [comment]
[crash-2021-06-01_22.43.08-client.txt](https://github.com/Minenash/Enhanced-Attack-Indicator/files/6580491/crash-2021-06-01_22.43.08-client.txt)
yep

**Comment by legosteenjaap** [comment]
I think i have found the problem. I tested this mod in a dev environment and now it works, weird. I think i will try to compile it now to test if it works.

**Comment by Minenash** [comment]
On my side, I did also test it on my normal Minecraft client

**Comment by legosteenjaap** [comment]
I compiled it and now it works (first crashed with canvas tough), maybe the modrinth version is outdated (i used version 1.0.2).

**Comment by Minenash** [comment]
Okay, so it definitely is something to do with the modrinth release, but the thing is, I didn't make any changes to the mod. However, somehow the build that was released is missing this in the refmap:
```
"com/minenash/enhanced_attack_indicator/mixin/ClientPlayerInteractionManagerAccessor": {
      "currentBreakingProgress": "field_3715:F"
    }
```

**Comment by Minenash** [comment]
I will re-release it with the new build (even if I didn't actually change anything, thanks yarn/loom)

**Comment by legosteenjaap** [comment]
Oh weird.

**Comment by Minenash** [comment]
https://github.com/Minenash/Enhanced-Attack-Indicator/releases/tag/v1.0.2%2B1.17
https://modrinth.com/mod/enhanced-attack-indicator/version/SqJt8WRc
