### ISSUE TITLE
[enhancement] snapshot support

### ISSUE THREAD

**Issue by vos6434** [Minenash/Enhanced-Attack-Indicator#15]
Could you support 1.18 snapshots? This is a great QOL mod and I use it all the time.

**Comment by EysseW** [comment]
Same here, since 1.18 came out these are not snapshot anymore, but I still want it.

**Comment by vos6434** [comment]
The 1.17 build works with 1.18.

**Comment by EysseW** [comment]
aha, thanks!

**Comment by EysseW** [comment]
I noticed it doesn't on my machine

**Comment by vos6434** [comment]
Does it say it requires 1.17?

**Comment by EysseW** [comment]
yes

**Comment by vos6434** [comment]
edit the fabric mod json file inside the jar, replace minecraft 1.17 with 1.18.

**Comment by EysseW** [comment]
> edit the fabric mod json file inside the jar, replace minecraft 1.17 with 1.18.

I have, but now how do I turn it back into a .jar?

**Comment by vos6434** [comment]
Don't extract. Instead open the jar with 7zip/WinRAR and replace the fabric mod json.

**Comment by EysseW** [comment]
Do you know how to do that on linux? I don't get how the tools work they give me.

**Comment by EysseW** [comment]
Nevermind I got it working, thanks!

**Comment by srnyx** [comment]
@Minenash 1.19 has released, please update!!

**Comment by Minenash** [comment]
Don't plan to support snapshots, and 1.19 has been released
