### ISSUE TITLE
Game crash when entering the mod's configure menu

### ISSUE THREAD

**Issue by 1unar-Eclipse** [Minenash/Enhanced-Attack-Indicator#21]
Attempting to open the configure menu will cause the game to crash.
[The crash report](https://github.com/Minenash/Enhanced-Attack-Indicator/files/10689668/crash-2023-02-08_15.29.42-client.txt)
![My other mods](https://user-images.githubusercontent.com/74077800/217644453-d57e782b-2f11-481e-9473-86779acf2389.png)

**Comment by cjtganzon** [comment]
same here. using quilt

**Comment by ActualBest** [comment]
Can confirm. I am also using Quilt.

**Comment by Chaose3** [comment]
Same here with Fabric

**Comment by srnyx** [comment]
Happening to me too;
**Minecraft:** 1.19.4
**Loader:** Fabric 0.14.19
**Enhanced Attack Indicator:** v1.0.3+1.19
**Common mods:** Capes, Fabric API, Fabric Language Kotlin, Ferritecore, Lambdynamiclights, LazyDFU, Lithium, Malilib, MiniHUD, Mod Menu. Reese's Sodium Options, Sodium Extra, Sodium, Starlight

**Comment by Minenash** [comment]
Until today it wasn't out for 1.19.4, which is why it crashed for you @srnyx 

As for everyone else, does the new 1.19.4 version have this problem? With how long 1.19.4 has been out, and with 1.20 around the corner, I'm not sure it's worth investigating 1.19.3

**Comment by 1unar-Eclipse** [comment]
Game no longer crashes!
