### ISSUE TITLE
Most tools don't work

### ISSUE THREAD

**Issue by Quadragintillion** [Minenash/Enhanced-Attack-Indicator#31]
The attack indicator for any tool with attack damage (other than swords) doesn't show up.

**Comment by Minenash** [comment]
Look in the config screen. There's options to turn them back on. 

It's disabled to as the mods and block breaking progress as one of the things it shows, and with the attack cool down, it can look weird. And since almost no one uses pickaxes as a weapon, it seemed like a fair default

**Comment by Fyoncle** [comment]
> Look in the config screen. There's options to turn them back on.
> 
> It's disabled to as the mods and block breaking progress as one of the things it shows, and with the attack cool down, it can look weird. And since almost no one uses pickaxes as a weapon, it seemed like a fair default

LMFAO who using pickaxes as a weapon?

**Comment by LordEnder-Kitty** [comment]
> > Look in the config screen. There's options to turn them back on.
> > It's disabled to as the mods and block breaking progress as one of the things it shows, and with the attack cool down, it can look weird. And since almost no one uses pickaxes as a weapon, it seemed like a fair default
> 
> LMFAO who using pickaxes as a weapon?

Minors

**Comment by Quadragintillion** [comment]
> Look in the config screen. There's options to turn them back on.
> It's disabled to as the mods and block breaking progress as one of the things it shows, and with the attack cool down, it can look weird. And since almost no one uses pickaxes as a weapon, it seemed like a fair default

Any other tool as in axes which are used a ton as a weapon

**Comment by Minenash** [comment]
Not really. Though because axes are more often used, I added a separate option for specifically axes
