### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by Madis0** [Minenash/Enhanced-Attack-Indicator#5]
That hopefully isn't just a screenshot

**Comment by Minenash** [comment]
Any ideas?

**Comment by Madis0** [comment]
It is unfortunate that the vanilla "ready" indicator already includes a plus, but I was thinking that with more pronounced colors.

**Comment by Madis0** [comment]
![icon](https://user-images.githubusercontent.com/8611110/107806618-c17e2800-6d6f-11eb-9e5d-ee7046d167b4.png)

**Comment by Minenash** [comment]
Oh damn, that looks good. Not sure if I'd be tacky m, but maybe have the + be gold?

**Comment by Madis0** [comment]
Sure.
![icon](https://user-images.githubusercontent.com/8611110/107811601-170a0300-6d77-11eb-9079-c005f8bf6561.png)

**Comment by Minenash** [comment]
Hmm, now that I'm at my pc, I'll try a more yellow-gold, and if depending on how that looks, I'll either use that, or the green one

**Comment by Minenash** [comment]
Okay, this is will be the icon. I added more spacing between the sword and plus (4px), and then moved the whole thing up (2px). And thanks to tinypng, it's only 232 bytes!
![icon](https://user-images.githubusercontent.com/12193049/107824701-ea8ec080-6d4f-11eb-8efb-f49ac4e26179.png)
