### ISSUE TITLE
Mod crashes without modmenu.

### ISSUE THREAD

**Issue by Kichura** [Minenash/Enhanced-Attack-Indicator#7]
When minecraft is started with this mod, it checks the code for modmenu api classes; and if it cannot find those then the game normally should just continue without it.

However instead of continuing, it crashes instead by saying that it cannot find anything.

**Comment by Kichura** [comment]
https://pastebin.com/raw/tR1TeQvS - crash-report file in case it's needed.

**Comment by Kichura** [comment]
Perhaps make a fix to this one if capable or is it impossible?

**Comment by Minenash** [comment]
I'll push a fix tonight

**Comment by Kichura** [comment]
Late response but: Thanks for reminding me that a fix is being pushed soon.

**Comment by Minenash** [comment]
43 "nights" latter, and this has been fixed in v1.0.1
